name:
  name: 'Tradecube-Reporting' # {{ .Values.name.name }}

env:
  HTTPPrefix: http://                  # {{ .Values.env.HTTPPrefix }}
  HTTPSPrefix: https://                # {{ .Values.env.HTTPSPrefix }}
  certPassword: ''                     # {{ .Values.env.certPassword }}
  certificateNamePrefix: /certs/       # {{ .Values.env.certificateNamePrefix }}     
  certificateNameSuffix: <not-set>     # {{ .Values.env.certificateNameSuffix }}
  environment: <not-set>               # {{ .Values.env.environment }}
  apiDomain: api.tradecube.io          # {{ .Values.env.environment }}
  apiPort: 443                         # {{ .Values.env.apiPort }}

service:
  port: 80       # {{ .Values.service.port }}
  targetPort: 80 # {{ .Values.service.targetPort }}
  httpPort: 80   # {{ .Values.service.httpPort }}
  httpsPort: 443 # {{ .Values.service.httpsPort }}
  protocol: TCP  # {{ .Values.service.protocol }}

ingress:
  ingressReportingDomain: reporting

type:
  configmap: -config-map  # {{ .Values.type.configmap }}
  deployment: -deployment # {{ .Values.type.deployment }}
  ingress: -ingress       # {{ .Values.type.ingress }}
  pod: -pod               # {{ .Values.type.pod }}
  service: -service       # {{ .Values.type.service }}

component:
  reporting: -reporting         # {{ .Values.component.reporting }}

letsencrypt:
  clusterIssuer: <TBA>        # {{ .Values.letsencrypt.clusterIssuer }}

certificate:
  volumeName: <TBA> # {{ .Values.certificate.volumeName }}

image:
  repository: ctrmcubed        # {{ .Values.image.repository }}
  pullPolicy: IfNotPresent     # {{ .Values.image.pullPolicy }}
  reporting: tradecube-reports # {{ .Values.image.reporting }}
  reportingtag: latest-dev     # {{ .Values.image.reportingtag }}

port:   
  reporting: 44370     # {{ .Values.port.reporting }}
  reporting-ssl: 44365 # {{ .Values.port.reporting-ssl }}

restartPolicy:
  reporting: Always # {{ .Values.restartPolicy.reporting }}

replicas:
  reporting: 1 # {{ .Values.replicas.reporting }}

strategy:                
  type: RollingUpdate # {{ .Values.strategy.type }}
  maxSurge: 1         # {{ .Values.strategy.maxSurge }}
  maxUnavailable: 0   # {{ .Values.strategy.maxUnavailable }}

readinessProbe:           
  path: /health           # {{ .Values.readinessProbe.path }}
  initialDelaySeconds: 10 # {{ .Values.readinessProbe.initialDelaySeconds }}
  periodSeconds: 10       # {{ .Values.readinessProbe.periodSeconds }}
  timeoutSeconds: 2       # {{ .Values.timeoutSeconds.timeoutSeconds }}

livenessProbe:
  path: /health            # {{ .Values.livenessProbe.path }}
  initialDelaySeconds: 120 # {{ .Values.livenessProbe.initialDelaySeconds }}
  periodSeconds: 30        # {{ .Values.livenessProbe.periodSeconds }}
  timeoutSeconds: 2        # {{ .Values.timeoutSeconds.timeoutSeconds }} 