name: $(build.buildId)_$(Date:yyyyMMdd)_$(BuildDefinitionName)_$(SourceBranchName)
trigger:
- develop
resources:
- repo: self
pool:
  vmImage: ubuntu-latest
variables:
  projectName: tradecube-reports
  versionMajor: 0
  versionMinor: 0
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'ctrmcubed/tradecube-reports'
    command: 'buildAndPush'
    Dockerfile: '**/src/TradeCube-Reports/Dockerfile'
    buildContext: 'src'
    tags: |
      $(Build.BuildId)
      latest-dev