kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}{{ .Values.type.configmap }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:  
  TRADECUBE_REPORTS_HTTPS_PORT: {{ .Values.env.environment }}
  TRADECUBE_REPORTS_CERT_NAME: {{ .Values.env.certificateNamePrefix }}{{ .Values.env.certificateNameSuffix }}
  TRADECUBE_REPORTS_CERT_PASSWORD: '{{ .Values.env.certPassword }}'
  TRADECUBE_API_DOMAIN: {{ .Values.env.environment }}
  TRADECUBE_API_PORT: {{ .Values.env.environment }}
